import logoV from './icons/V_Logo.svg';
import logoNameB from './icons/LogoName.svg';
import logoNameW from './icons/LogoName_white.svg';

import {
  BadgeCheck,
  Bell,
  ChevronsUpDown,
  CreditCard,
  LogOut,
  Sparkles,
  CircleUserRound,
  RectangleEllipsis,
  AudioWaveform,
  BookOpen,
  Bot,
  Command,
  Frame,
  GalleryVerticalEnd,
  Map,
  PieChart,
  Settings2,
  SquareTerminal,
  Folder,
  Forward,
  MoreHorizontal,
  Trash2,
  LayoutDashboard,
  ReceiptText,
  SquareGanttChart,
  ShoppingBasket,
  Ticket,
  Contact,
  Shield,
  Users,
  GroupIcon,
  ArrowLeft,
  ShieldBan,
} from 'lucide-react';
import { Box, ShoppingBag, ClipboardList } from 'lucide-react';

export const LogoIcons = {
  logoV,
  logoNameB,
  logoNameW,
};

export const Icons = {};

export const ComponentsIcons = {
  CircleUserRound,
  BadgeCheck,
  Bell,
  ChevronsUpDown,
  CreditCard,
  LogOut,
  Sparkles,
  RectangleEllipsis,
  AudioWaveform,
  BookOpen,
  Bot,
  Command,
  Frame,
  GalleryVerticalEnd,
  Map,
  PieChart,
  Settings2,
  SquareTerminal,
  Folder,
  Forward,
  MoreHorizontal,
  Trash2,
  LayoutDashboard,
  ReceiptText,
  ShoppingBasket,
  SquareGanttChart,
  Ticket,
  Contact,
  Box,
  ShoppingBag,
  ClipboardList,
  Shield,
  Users,
  GroupIcon,
  ArrowLeft,
  ShieldBan,
};
